dist: trusty
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_1a2cff5fdb56_key -iv $encrypted_1a2cff5fdb56_iv
  -in credentials.properties.enc -out credentials.properties -d
- chmod +x scripts/*
- scripts/install-dependencies.sh
install: scripts/gettoolchains.sh
script: scripts/readytorock.sh
env:
  global:
  - VER="1.26.2-YDS"
  - STATUS="stable"
  matrix:
  - TO_BUILD="arm arm64"
  - TO_BUILD="x86 x86_64"
  - TO_BUILD="mips mips64"
  - TO_BUILD="mipseb"
  - TO_BUILD="boxemup"
after_success:
- test "$TO_BUILD" != "boxemup" && exit
- scripts/settags.sh
deploy:
  provider: releases
  api_key:
    secure: DNJ3D7T1YZqAJA0wxRaZLYOzs0HmRfC5MOdZkl3Pz4X/Ip7+KJrW7ujWlKrkvL/bM+4aN2tfn/RKzdl7KRxqGRicUv/BRIPOvlzrLYF75VLT4kTGEPjHmjQTddjyI+ms67CHGXISVdJRqOu4LeFgvcPfNoVyqTfOEvNzQ3cex/1AG+nx5Bu9kMY+UTC99Jt6K8UyxQb4IftUvrNb7O9qwmf6CR8f8SW6hs474uu2V4ST70YzEhowNuTZ1Gvw/86FbkGtRQQclId4wOx9gGQ76gM3Ygh8pdM1ZJ8PsgyjAVRzl68iGcB+f6Wy3obH57wWnacGxjM1LWEczcSRITvWIp0QzykjqDA9CYb5Za6JiaSeeaA28VyPUnt7Rp+tvEHetWLa0o5u+oTBhIe74FWUcFdf6WAx3b8a70MHUj7mtGC7sTmuxUZPcvYuwWRizDuEXrFXO41mIZgS25+sgSbZc47UNvJ4j1tuL7byNPb6ILM8boGjoCraMFe5IHUuOMnVGmCNZpiDTO2tBDofXPNe581ow2+rH5gKg5qEu4zdLIiEFmOlH+MDNG7x84igqKFzef9RClPvudv4CxR+ED+j9ax/HkU4o0nc882GvRpGyr21yJBakcZwU6uehrFcl5OoZS6cO0yOa7xnDnJUHh2OfSpsI6H0kJ9eeUaiGoxD1YI=
  file:
      - "bbx/out/*/*zip"
      - "bbx/out/*/Tars/*tar.gz"
  file_glob: true
  skip_cleanup: true
  on:
    repo: yashdsaraf/bb-bot
